
all:	caso0 caso1 caso2 caso3 caso4 caso5 caso6 caso7 caso8 caso9 caso10

clean:
	rm -rf caso0 caso1 caso2 caso3 caso4 caso5 caso6 caso7 caso8 caso9 caso10
	rm -rf caso?.o caso??.o caso??.o *~ *log
	
caso0: caso0.c
	gcc -o caso0 caso0.c ../bin/support.o -L../lib -lcthread -Wall
caso1: caso1.c
	gcc -o caso1 caso1.c ../bin/support.o -L../lib -lcthread -Wall
caso2: caso2.c
	gcc -o caso2 caso2.c ../bin/support.o -L../lib -lcthread -Wall
caso3: caso3.c
	gcc -o caso3 caso3.c ../bin/support.o -L../lib -lcthread -Wall
caso4: caso4.c
	gcc -o caso4 caso4.c ../bin/support.o -L../lib -lcthread -Wall
caso5: caso5.c
	gcc -o caso5 caso5.c ../bin/support.o -L../lib -lcthread -Wall
caso6: caso6.c
	gcc -o caso6 caso6.c ../bin/support.o -L../lib -lcthread -Wall
caso7: caso7.c
	gcc -o caso7 caso7.c ../bin/support.o -L../lib -lcthread -Wall
caso8: caso8.c
	gcc -o caso8 caso8.c ../bin/support.o -L../lib -lcthread -Wall
caso9: caso9.c
	gcc -o caso9 caso9.c ../bin/support.o -L../lib -lcthread -Wall
caso10: caso10.c
	gcc -o caso10 caso10.c ../bin/support.o -L../lib -lcthread -Wall





